### ISSUE TITLE
Can't find helm chart - mysql

### ISSUE THREAD

**Issue by yokawasa** [neilpeterson/open-service-broker-azure-samples#2]
Can you please share helm chart on osba-mysql-demo? I tried to install as instruction but looks like it doesn't exists in the repo below
```
helm repo add azure-samples https://azure-samples.github.io/helm-charts/
helm install azure-samples/osba-mysql-demo
```
Anyway, thank you for sharing the great sample!

**Comment by neilpeterson** [comment]
@yokawasa - thanks for checking these out and for sending the note / issue.

The MySQL sample has been updates and the chart now works.

**Comment by yokawasa** [comment]
@neilpeterson  thanks alot for your prompt reponse! I was able to install the package!
